### ISSUE TITLE
subtopics

### ISSUE THREAD

**Issue by philchalmers** [friendly/statquotes#1]
So there are really two main approaches to accessing subtopics in this hierarchical structure: add a new argument `statquotes(..., subtopic = 'name'),` or to chain the already existing `topic` input. Something like this:

``` r
statquotes(topic = 'statistics') #sample from topic
statquotes(topic = 'science:Box Quotes') #sample from subtopic within science
```

I'm leaning towards the second way because then there would be no limit to the amount of hierarchical levels if more columns are added to `quotes`. E.g, `topic = 'science:famous:Box Quotes`, which would just require a string split and then looping over the respective levels. Thoughts?

**Comment by friendly** [comment]
Yes, I agree with the second approach.  Note that if in `statquote()` we just paste together the `topic` and `subtopic` fields in a local `topic` then, because we're using `stringr::str_detect()`, `statquote(topic="box")` should do the same as your 2nd example.

**Comment by philchalmers** [comment]
Added. In the same spirit I think adding two new inputs would be helpful to quickly subset via author/source and fuzzy text matching of the quotes. The former would largely avoid the need for having 'Box' and 'Tukey' subtopics, while the latter can be used to roughly see if a quote has been defined already.

**Comment by mattsigal** [comment]
Yeah, I think separating the author field into its own input is a good idea.

**Comment by mattsigal** [comment]
First stab at this functionality, added author search query and documentation. #todo: allow for user to utilize _both_ topic and author fields?

**Comment by philchalmers** [comment]
Looks good. I think interacting the fields may be overkill because it's just to make a more fine-tuned sampler. 

I thought a bit more about searching through the quotes directly, but I guess now that `data(quotes)` is exposed it's easy enough just to use 

``` r
with(quotes, text[str_detect(text, 'learn by doing')])
```

....though it's a bit awkward, and also doesn't support fuzzy matching like `base::agrep`. 

Maybe this should be made into a separate function `search_quotes <- function(quote, fuzzy = TRUE)`, potentially only for us devs to use to determine if a new quote has already been defined?

**Comment by mattsigal** [comment]
In https://github.com/friendly/statquotes/commit/a84196ee69d6ff3c7ed71afe5978062e271b5585 I added `search_quotes()`, which I think is structured logically. Basically, you can do fuzzy search (using `agrep()`), or strict, and it will return a data.frame with all matching cases, instead of a sample.  I think this will be useful for users, especially if the quotes database continues to grow.

**Comment by friendly** [comment]
this is great -- it was the next thing I was going to propose. However, rather than always searching **all** fields, perhaps a `fields=` arg could be added, with default

```
fields = c("topic", "subtopic", "text", "source")
```

where those are used to create `merged` in the function.

**Comment by mattsigal** [comment]
Oh, I like that.  I'll tinker with it right now.

**Comment by mattsigal** [comment]
Added fields argument, and I think it is working properly but needs testing.

**Comment by friendly** [comment]
Thanks for this.  I haven't tested, but now the package builds with no errors, warnings or notes.

I think this is getting near enough for CRAN
