### ISSUE TITLE
as.latex.statquote

### ISSUE THREAD

**Issue by friendly** [friendly/statquotes#11]
It would be useful to be able to print a few statquotes in latex form.  I took a stab at this, creating `inst/as.latex.statquote.R`.  But I get errors I don't grok.

    > ll <- search_quotes("Tukey")
    > as.latex.statquote(ll)
    Error in if (data$TeXsource[i] != "") data$TeXsource[i] else data$source[i] : 
      argument is of length zero

**Comment by philchalmers** [comment]
I updated the code to make this work for your function. Turns out the `TeXsource` column was not being built into the R binary file.

**Comment by friendly** [comment]
Thanks, Phil
Just this morning I wanted to do this for a quote from Florence Nightingale I'd like to use in my current book.

**Comment by philchalmers** [comment]
No problem. Should take trivial effort to export this function in the package as well. I think just the `require()` statement needs to be added to the `DESCRIPTION::imports`  field, and otherwise it should check out clean. I can go ahead and do this if you'd prefer this function to more easily accessible.

**Comment by friendly** [comment]
Yes, please go ahead and move `as.latex.statquote.R` from `inst/` to `R/`.  It will need a Roxygen header, in which you can add `@imports` or `@importFrom stringr ...` rather than `require()`.

Is the argument for the generic `as.latex()` function `data`?  I often get hung up on this.
Thanks for taking this on.

**Comment by philchalmers** [comment]
Added. Re: `as.latex()` vs `as.latex.statquote()`, it just depends on if a suitable generic has been imported to the package (defaults like `print()` and such are, but `as.latex()` is not a standard generic without being defined/imported elsewhere).

**Comment by friendly** [comment]
OK, but I thought that there was an `as.latex()` generic elsewhere else.  Wouldn't it be better not to mask that in other packages and have an `as.latex.statquote` method?

**Comment by philchalmers** [comment]
I can't find an `as.latex()` method anywhere in my set of currently installed packages.... so it's either really rare, or maybe it doesn't exist at all?

**Comment by friendly** [comment]
Surprising. I can't either.  Leave it as is for now.
