### ISSUE TITLE
need an as.markdown method

### ISSUE THREAD

**Issue by friendly** [friendly/statquotes#14]
We have plain text (console style) output, `as.latex()`, so why not `as.markdown()` --- that seems pretty simple.

**Comment by kwstat** [comment]
Added in dev-tags branch.

**Comment by friendly** [comment]
Hi Kevin
You've been busy on this;  I'm currently working on other packages.
what is the current status?  Have you simply moved all the stuff related to tags into the `dev-tags` branch?
Should this be what I'll work on now?
