### ISSUE TITLE
topics vs. tags

### ISSUE THREAD

**Issue by friendly** [friendly/statquotes#15]
If statquotes is to go further, and accommodate new uses, the DB should probably move from the original `topic`, `subtopic` hierarchical model to something based on `tags` from a recognized vocabulary.   
Could just add a `tags` field for now, 
    
    tags <- paste(topic. subtopic, sep=";")

Thoughts?

**Comment by kwstat** [comment]
The `dev-tags` branch uses `tags` instead of `topic`.
