### ISSUE TITLE
adding `inst/readQuotes.R` to read new quotes and append to `quotes` database

### ISSUE THREAD

**Issue by friendly** [friendly/statquotes#18]
I've done some work on a new function,  `inst/readQuotes.R`, designed to read new quotations from either an ascii TXT file for a latex TEX file.  The goal is to make it easier, at least for us, but maybe others, to add new quotations.   `inst/quotes-new2.txt` is collects some quotes I'd like to add to the database.

The TXT file format looks like this: Each quote is in a single line, followed by `--- source`

![image](https://user-images.githubusercontent.com/456353/79130271-b126a680-7d74-11ea-8b3a-74a7190a508b.png)

I tried to follow the scheme used for TEX files, but there are (at least) two bugs in my code:

    # patterns for quotations and sources
    quotpat <- "^[^#-](.*)"               #quotes are lines that don't begin with "#" or "-"
              # FIXME:  for some reason, the first letter of the quote is not captured.
    quotes <-  str_match(text, quotpat)

Also,

    # FIXME: There is a one-off error -- text & source appear as seaprate observations
    quotes <- quotes[!(is.na(quotes$text) & is.na(quotes$source)),]

What I get looks like this:

![image](https://user-images.githubusercontent.com/456353/79131042-f26b8600-7d75-11ea-987c-add22623d3ec.png)

**Comment by friendly** [comment]
These bugs have been fixed. I will add `readQuotes()` as a package function.

**Comment by kwstat** [comment]
No longer needed.
