### ISSUE TITLE
search_quotes() problems

### ISSUE THREAD

**Issue by friendly** [friendly/statquotes#19]
There are a number of problems with `statquotes::search_quotes()`

- Sometimes it cannot find items I know should match; 

    > statquotes::search_quotes("Wells")
    Error in statquotes::search_quotes("Wells") : 
      The search parameters 'Wells' did not match any items.

the database has:

    234
    qid: 234
    topic: Statistics
    text: Statistical thinking will one day be as necessary for efficient citizenship as the ability to read and write.
    source: H.G. Wells, Mankind in Making, 1903

- sometimes it picks up only one of multiple matches;

    > statquotes::search_quotes("Neumann")
    With four parameters I can fit an elephant, and with five I can make him wiggle his trunk. 
    --- John von Neumann 

but there are 3 items in the database

    169
    169
    Science
    With four parameters I can fit an elephant, and with five I can make him wiggle his trunk. 
    John von Neumann

    250
    250
    Computing
    Any one who considers arithmetical methods of producing random digits is, of course, in a state of sin.
    John von Neumann

    251
    251
    Science
    With four parameters I can fit an elephant, and with five I can make him wiggle his trunk.
    John von Neumann, quoted by Freeman Dyson

Also, using `fuzzy = TRUE` gives a bewildering set of results, most of which are way too fuzzy. E.g.: try

    statquotes::search_quotes("Twain", fuzzy=TRUE)

**Comment by friendly** [comment]
Fixed by adding `ignore_case` option

**Comment by kwstat** [comment]
Seems to be working now.
```
R> search_quotes("Wells")

Statistical thinking will one day be as necessary for
efficient citizenship as the ability to read and
write.
--- H.G. Wells
R> search_quotes("Neumann")

With four parameters I can fit an elephant, and with
five I can make him wiggle his trunk.
--- John von Neumann

Any one who considers arithmetical methods of
producing random digits is, of course, in a state of
sin.
--- John von Neumann

With four parameters I can fit an elephant, and with
five I can make him wiggle his trunk.
--- John von Neumann
```
