### ISSUE TITLE
expose_quotes()?

### ISSUE THREAD

**Issue by friendly** [friendly/statquotes#2]
`statquote()` hides the `quotes` data in an environment, which is good for most uses.  But what if someone wants to do something else with them?

I propose a function, `expose_quotes()` which simply makes the `quotes` data frame visible in the global environment.  Not sure how to do this, but it's probably simple.

**Comment by philchalmers** [comment]
Should we just expose the `.RData` file directly then, and include formal HTML documentation in the usual flavour? Otherwise, a simple 

``` r
#' Title
#'
#' Description ....
#' @export
expose_quotes <- function() .get.sq() 
```

would do the trick if documenting the object isn't a big deal.

**Comment by philchalmers** [comment]
Or to that end, just change `.get.sq()` to `expose_quotes()` and export. Either way, it depends how documented the data.frame should be.

**Comment by friendly** [comment]
OK, I committed an attempt at this; untested.

**Comment by philchalmers** [comment]
If the dataset is completely documented and available then there's really no need for all these extra extractors or environments. E.g., if the `inst/quotes.RData` is just moved to `data/quotes.RData` then operations like `data(quotes)` will now work fine. 

I prefer this route too (wasn't initially sure how exposed you wanted the object to be), and I'll adjust/remove the dead code later.

**Comment by philchalmers** [comment]
No need for public exposing functions now, just use `data(quotes)` and `help(quotes)` PRN.
