### ISSUE TITLE
Add method to automatically convert text quotes to rda

### ISSUE THREAD

**Issue by kwstat** [friendly/statquotes#28]
Phil wrote: I'm not a fan of the current building process where manual steps must be taken prior to CRAN submission. Personally, I would add a testthat structure where local checks (and incoming pull requests) would automatically build the new .rda files when R CMD check is called, though on the CRAN check engines this behaviour is disabled (via testthat::skip_on_cran()). That way any CRAN submission that has been checked locally will have the correct files without having accidentally called the initializers manually, and encourages the build chain through individual contributions to help deter future errors.

**Comment by friendly** [comment]
As a step in that direction, I made the script in `data-raw/convert_quotes_to_rda.R` use an internal function, `readQuotes(file)`. This could be pulled out and made more general.

**Comment by kwstat** [comment]
The `testthat` package is not supposed to have side-effects. Roxygen has `@eval` which can execute functions during the *documentation* process, so that's the method I chose.  From now on, this is how the process works:

1. Edit `data-raw/quotes-raw.txt`
2. Run `devtools::document()`.  This will parse the `quotes-raw.txt` into a dataframe and then write `data/quotes.rda`.
3. Test, check, send to CRAN.


# Research notes for ways to include the quotes database in the statquotes package.

https://blog.r-hub.io/2020/05/29/distribute-data/
Discussions about various ways to include data in packages.

https://stackoverflow.com/questions/73838516/how-do-i-rebuild-data-raw-using-roxygen2
After reading more documentation, I found the answer to the question. The @examples idea from @r2evans helped me find something that is more directly targeting something like this. I used #' @eval my_function() where my_function() is an exported function in the package that builds the data and generates the documentation for the data.

https://community.rstudio.com/t/in-an-r-package-build-build-data-from-script-in-data-raw/34308
Points to an example using "tests".
Also talks about using a Makefile.

https://mpn.metworx.com/packages/roxygen2/7.1.0/articles/rd.html#evaluating-arbitrary-code
Shows how to use @eval tag.


## .onLoad

We could use tools:::.onLoad to read the quotes at startup from inst/extdata when a package is loaded.

Pro: Only one copy of the quotes file instead of two copies.

Con: Takes about 1 second to parse the quotes at startup

## testthat

Could "testthat" package be used to automate data creation? Unclear, since testthat has already loaded the package functions/data

Pro:

Con: testthat is not supposed to have side effects to the code.

## roxygen @eval

Pro: Updates the quotes database *before* testing / checking.

Con: There are few examples of @eval being used.

`#' @eval sprintf("%s", Sys.time())`

In the following example, the author uses @eval to automatically document data using Roxygen.

https://jsta.rbind.io/blog/automated-roxygen-documentation-of-r-package-data/
https://github.com/jsta/autodatadoc/blob/master/R/data.R

## sysdata

Pro: Having internal data (like a quotes database) is really what `sysdata` is designed for.

Con: Hides the quotes data object. Have to manually update sysdata:
```
#Create sysdata for the package
#quotedata <- dat
#usethis::use_data(quotedata, internal=TRUE, overwrite=TRUE)
#if(FALSE){
#file.info("c:/one/rpack/statquotes/R/sysdata.rda")
#file.size("c:/one/rpack/statquotes/R/sysdata.rda") in bytes
}
```

**Comment by philchalmers** [comment]
The current build chain seems to be working well, from what I can tell. Should this issue be closed at this point?

**Comment by friendly** [comment]
This does seem like a stale issue that should have been closed long ago. let's wait a bit to see if @kwstat agrees.

**Comment by kwstat** [comment]
Yes, close.
