### ISSUE TITLE
Collected quotes vignette?

### ISSUE THREAD

**Issue by friendly** [friendly/statquotes#31]
Looking at the `fortunes` package, the one vignette simply prints them all with full information and `qid` numbers. 
https://cran.r-project.org/web/packages/fortunes/vignettes/fortunes.pdf 

Shouldn't be that hard. Something like a loop or apply using `as.markdown()?  But it might be nice to also print the associated tags.

**Comment by philchalmers** [comment]
Added branch `issue31`  with an `.Rmd` file to generate the quotes into a large markdown file. Here's a snippet when compiled

![Screenshot (1)](https://github.com/friendly/statquotes/assets/1274464/55a6f1b1-9646-48a5-8526-35b018c4d119)

**Comment by kwstat** [comment]
Looks good, but I find the subscript format to be visually a bit distracting.  I'd probably put the number and the hashtag all on the same line with the other text.  But do what you want.

**Comment by philchalmers** [comment]
Personally, I like the subscript for the hashtags (tried earlier on the same line, and some tags were too distracting given how much space they occupied). Agreed that a  `"1. Quote "` structure for the quotations would be nicer, so I'll make that change.

**Comment by philchalmers** [comment]
Latest version.

![Screenshot (9)](https://github.com/friendly/statquotes/assets/1274464/683fe217-ad00-4fe2-9a71-03a3cf06abdb)

**Comment by friendly** [comment]
I like the smaller, subscript font for tags also. I'm particularly glad the reference is also, which I think should also be the default for `search_quotes()`
