### ISSUE TITLE
Add `ctx:` flag?

### ISSUE THREAD

**Issue by philchalmers** [friendly/statquotes#32]
I touched up the `find_duplicate_quotes()` function (slow as it is...), and came across two issues (I'll open the next issue shortly). The first is that some of the quotes were duplicates in the sense that they contained roughly the same strings, however included more contextualization. For instance, 

```
> statquote(ind=489)

The result is that non-statisticians tend to place undue reliance on single 'cookbook' techniques, and it has for example become
impossible to get results published in some medical, psychological and biological journals without reporting significance values
even if of doubtful validity. It is sad that students may actually be more confused and less numerate at the end of a 'service
course' than they were at the beginning, and more likely to overlook a descriptive approach in favour of some inferential method
which may be inappropriate or incorrectly executed.
--- C. Chatfield, The initial examination of data, 1985. Journal of the Royal Statistical Society, Series A 148: 214-253.

# compared to
> statquote(ind=494)

...it has ... become impossible to get results published in some medical, psychological and biological journals without reporting
significance values even when of doubtful validity.
--- C. Chatfield, The initial examination of data, 1985. Journal of the Royal Statistical Society, Series A 148: 214-253.
```

There's around 10 quotes that have this additional context information. 

Two approaches are possible: 

- Rather than treating them as duplicates it might be best to add a `cxt:` flag to indicate the additional full context of the quotation, separating the pithy quotes. More work, and would require flags like `context = TRUE` in various areas of the package, but supporting larger text bodies might be nice (e.g., in book chapters)
- Keep one of the quotations only (full context or concentrated). I'm currently in favour of retaining the more pithy versions of the quotes, unless the full version is quite short, but don't feel conformable making such an executive call alone. 

Thoughts on how to proceed?

**Comment by philchalmers** [comment]
I suppose there is an option 3: leave the longer quotes in as-is. The only real downside is that the word clouds and other visual representations in the `README.md` file have small overrepresentations from the duplicates, so perhaps removing the tag information for the duplicates would be appropriate here too. I just find the behaviour of `search_quotes()` returning redundant hits a little unnecessaries (e.g., Box appearing twice below). 

```r
search_quotes("some are useful")

All models are wrong but some are useful.
--- George E. P. Box

All data are wrong, but some are useful.
--- Jim Kloet (after George Box), RStudio::Conf 2022

The fact that [the model] is an approximation does not necessarily detract from its usefulness because models
are approximations. All models are wrong, but some are useful.
--- George E P Box, 1987

All generative models are wrong, but some are useful.
--- Jared Lander, Copilot for R, 56:25
```

**Comment by friendly** [comment]
It is somewhat of a judgment call how much context to include in a quote, but generally my intention for statsquotes was that they be short, pithy and memorable -- the kind of thing one might want to use in writing to introduce or illustrate some topic/idea. 

By the idea of a `ctx` tag, I think you mean a longer version of the same quote that supplies wider context.  Interesting, but I think this might be overdoing things for a very small (??) number of quotes. And, doing this more generally would mean a great deal of work.

Let's leave things as they are for now.
