### ISSUE TITLE
Conflicting duplicates

### ISSUE THREAD

**Issue by philchalmers** [friendly/statquotes#33]
Some extra eyes on the following would be helpful to clean up the quotes book given some conflicting information (e.g., differing citation information, dates, etc). 

# Conflict 1

```r

> statquote(ind=558)

I contend that the general acceptance of statistical hypothesis testing is one of the most unfortunate aspects of 20th century
applied science. Tests for the identity of population distributions, for equality of treatment means, for presence of interactions,
for the nullity of a correlation coefficient, and so on, have been responsible for much bad science, much lazy science, and much
silly science. A good scientist can manage with, and will not be misled by, parameter estimates and their associated standard errors
or confidence limits.
--- Marks Nester, A Myopic View and History of Hypothesis Testing.

> statquote(ind=575)

I contend that the general acceptance of statistical hypothesis testing is one of the most unfortunate aspects of 20th century
applied science.
--- John A. Nelder, Discussion of Dr Chatfield's paper. 1985. Journal of the Royal Statistical Society A 148 : 238.
```

# Conflict 2

```r
> statquote(ind=629)

Randomness is a difficult notion for people to accept. When events come in clusters and streaks, people look for explanations and
patterns. They refuse to believe that such patterns - which frequently occur in random data - could equally well be derived from
tossing a coin. So it is in the stock market as well.
--- Didier Sornette, Why Stock Markets Crash: Critical events in complex financial systems, 2003

> statquote(ind=665)

Randomness is a difficult notion for people to accept. When events come in clusters and streaks, people look for explanations and
patterns. They refuse to believe that such patterns - which frequently occur in random data - could equally well be derived from
tossing a coin. So it is in the stock market as well.
--- Burton G Malkiel, "A Random Walk Down Wall Street", 1989
```

# Conflict 3

```r
> statquote(ind=387)

It was always important for the biometrician to take part in the field-work for most kinds of trials. A willingness to get our hands
dirty did much to dispel the distrust of the theoretician from Head Office, as well as giving us an appreciation of the practical
problems. Trials were always carried out to simulate farming conditions as much as possible. We had once advocated a change in wheat
plot lengths from 2 chains to 3, based on results from uniformity trials. It seemed a very good idea until a biometrician went to
help harvest a very good crop and found he had to lift and carry bags of over 100 lb, this being the yield from each plot. But the
local agriculturist in charge of the trial would never have reported this; he would only have gone on grumbling about those 'theory
guys' in Head Office forever.
--- Jean Heywood, A History of Statistics in New Zealand, edited by H.S.Roberts. p. 23-24.

> statquote(ind=689)

We had once advocated a change in wheat plot lengths from 2 chains to 3, based on results from uniformity trials. It seemed a very
good idea until a biometrician went to help harvest a very good crop and found he had to lift and carry bags of over 100 pounds,
this being the yield from each plot.
--- Jean Miller, A History of Statistics in New Zealand, H. S. Roberts.
```

**Comment by friendly** [comment]
Hmm. This is troubling, particularly in the case of Conflicts 1 & 2.

I don't recognize most of these quotes. Most likely from @kwstat, who has tended to use quite long quotes, where I think they should be short & pithy.

Going forward, one idea is to add a date-added (add:)  field  and perhaps a user (usr:) field, generated automatically in the function that adds quotes to the data base.

**Comment by philchalmers** [comment]
`git blame` can always be used to see who added the quotes + dates, so I don't think an `add` field is necessary given the current version control. 

https://github.com/friendly/statquotes/blame/master/data-raw/quotes_raw.txt

**Comment by friendly** [comment]
I had never tried git blame before.  Awesome

**Comment by kwstat** [comment]
Fix Conflict 1 via https://github.com/friendly/statquotes/commit/ec9ee83b18b4b6e5c5ad29260622227787e74c8e

**Comment by kwstat** [comment]
Conflict 2 is interesting.  The quote about "Randomness is a difficult notion" can be found here:
 https://archive.org/details/exploringmacroec0000sext_n6g7/page/230/mode/2up?q=%22randomness+is+a+difficult+notion%22
 and here:
 https://archive.org/details/exploringpsychol0004myer/page/22/mode/2up?q=%22randomness+is+a+difficult+notion%22
 and here:
 https://archive.org/details/isbn_9780300095319/page/152/mode/2up?q=%22randomness+is+a+difficult+notion%22

 
There are many editions of the book by Malkiel, none that I could find with the exact quote.  However, Internet Archive does not have a 1989 edition. But I found something similar, so I'll use that quote instead.
 
Fix via https://github.com/friendly/statquotes/commit/605388189858a96458d954b8a9975618bc7b088e

**Comment by philchalmers** [comment]
Thanks! Last conflict just requires a naming merge (Jean Heywood (neé Miller)), though requires a fix based on #32 as well. I'll push this fix and close the issue.

**Comment by friendly** [comment]
Great work on this. `find_duplicate_quotes()` earned it's keep!

**Comment by kwstat** [comment]
I added a url for the Jean Heywood Miller quote and removed the 2nd copy of the quote.
Fix via https://github.com/friendly/statquotes/commit/d114eb3dab1f78f702a5ef4f250c355506196eca
