### ISSUE TITLE
Release v 0.3-2?

### ISSUE THREAD

**Issue by friendly** [friendly/statquotes#34]
The recent changes adding the vignette and cite source are nice improvements, so we might push out this version, soonish, unless anyone foresees anything else.  Thoughts?

**Comment by philchalmers** [comment]
No objections here.

**Comment by friendly** [comment]
OK, thanks; unless @kwstat objects, I'll prepare a release this week.

**Comment by friendly** [comment]
Passes win-builder, with 1 (spurious) note re: misspelled words in DESCRIPTION (LateX, Rmarkdown).
Should be OK; I've run into this before.

**Comment by friendly** [comment]
DONE
