### ISSUE TITLE
Using an alternative to the .tex master file

### ISSUE THREAD

**Issue by philchalmers** [friendly/statquotes#4]
Just a place-holder issue for now and shouldn't affect the first release. I agree that the `.tex` master file approach currently used is a bit cumbersome and could be improved. I'm okay with either of these two approaches:
- switch to a `.csv` file as the master, with headings such as section/subsection to mimic the current structure. It would be easy from this file to generate a corresponding `.tex` file as well, similar to what is currently being used, so the other documentation which imports it wouldn't need to be modified (just a suitable function to go from `csv -> tex`
- use a markdown file in the similar spirit to directly convert to the forms we want (the markdown would be the kind of output we'd want in R). Would also convert naturally to tex (I think?), though the conversion to R might be a little hacked

At the moment I prefer the first option because it seems the most flexible and easier to work with.

**Comment by friendly** [comment]
In the  `.csv` approach, section/subsection headings are just fields rather than something special as in `.tex`. Any new quotes could just be added to the end, and a potential `csv -> tex` conversion could just sort on them.

**Comment by philchalmers** [comment]
```
section/subsection headings are just fields rather than something special as in .tex
```

Right, that's what I meant to convey. The file would need at least 4 header fields in each column: `topic`, `subtopic`, `quote` and `source`. After which the current .tex file could be reproduced pretty easily with some string substitutions (e.g., `*....* -> \emph{}`).

**Comment by philchalmers** [comment]
I've made some headway on this, though I didn't initially look closely at the `quotes.tex` file. It seems there are other elements not specifically wrapped within `\epigraph{}` (e.g., `see \url{...}`, some `verse` environments, general text, and so on), and even some comments that should probably be tracked still. I'm happy to add some additional elements to the master `.csv` file with all the quotes, though at the moments it's unclear what exactly to include.

**Comment by friendly** [comment]
Finished with this
