### ISSUE TITLE
revise print method for multiple quotes [develop]

### ISSUE THREAD

**Issue by friendly** [friendly/statquotes#5]
The `print` method for a `statquote` only handles one quote, and was simply modified from what Dirk did in `gaussfacts`.  It would be nice to extend this to multiple quotes, so that it could be used with the result of `search_quotes()`.  i.e. give something nicer for 

```
> search_quotes("fish")
    qid   topic subtopic
181 161 Science         
182 162 Science         
                                                                                                           text
181 Give a man to fish and he will eat for a day. Teach a man to fish and he will eat for the rest of his life.
182     Give a man a fish and he will eat for a day. Teach a man to fish and you lose a consulting job forever.
                 source
181     Chinese Proverb
182 Howard Wainer, 2016
> 
```

More like the combined result of

```
> statquote(161)
Give a man to fish and he will eat for a day. Teach a man to fish and he will eat for the rest of 
his life. 
--- Chinese Proverb 
> statquote(162)
Give a man a fish and he will eat for a day. Teach a man to fish and you lose a consulting job 
forever. 
--- Howard Wainer, 2016 
```

Any work on this should go on a new branch, e.g., `develop`

**Comment by philchalmers** [comment]
Sure, but it's nice to have the data.frame returned sometimes (used in other places in the package already). Maybe a new field `print = TRUE` to have the value returned as an `apply` set of print statements separated by a newline, and print = FALSE for internal use where a data.frame is needed.

**Comment by friendly** [comment]
There's no problem if `search_quotes()` returns an object of class `c("data.frame", "statquote")`.
This would require a more general `print.statquote` method.

**Comment by philchalmers** [comment]
Agreed. That sounds like the best approach.

**Comment by philchalmers** [comment]
@friendly do you still want these and other changes on a `devel` branch now that the package is public?

**Comment by friendly** [comment]
Yes;  I haven't gotten around to creating a devel branch.

**Comment by philchalmers** [comment]
Added to a `print` branched to be merged later. Now returns 

``` r
> search_quotes('fish')
Give a man to fish and he will eat for a day. Teach a man to fish and he will eat for the rest of 
his life. 
--- Chinese Proverb 

Give a man a fish and he will eat for a day. Teach a man to fish and you lose a consulting job 
forever. 
--- Howard Wainer, 2016 
>
```

**Comment by friendly** [comment]
This looks good -- exactly what I was thinking, to make `statquote()` return a data frame and modify the print method accordingly.  

I'm not sure of the status of your `print` branch wrt `master` and `devel`.  It looks like `devel` is already 3 commits ahead of `master`, so I'd accept a pull request of `print` to `devel`, and continue work from there.

**Comment by philchalmers** [comment]
They are different forks, both created at the current commit on `master`. So if you think `print` is ready just merge it into the `master` and delete the branch, and I can rebase the `devel` afterwords. I find that's the best approach when treating branches as features.

**Comment by philchalmers** [comment]
Oh it just registered what your last statement meant, sorry. I would advise against merging onto `devel` right now, as that approach could be abandoned if it doesn't quite work out. I could revert `devel` to make it the same as master, and add a new branch, say, `csv` with those experimental commits that are currently in `devel`. Sorry for the confusion.

**Comment by friendly** [comment]
OK, I didn't realize that `devel` was a fork to explore handling of CSV. Let's merge your `print` to `master` and go from there.  

Assuming it checks out, we can bump the package version and go from there.

**Comment by philchalmers** [comment]
Done to both. I also touched up the `quote_topics()` function, which was not exported, and added a `subtopics` logical. Also a simple `as.data.frame()` S3 method was added in case the `data.frame` format is really of interest to the user.
