### ISSUE TITLE
error with statquotes under R version 3.3.2 

### ISSUE THREAD

**Issue by friendly** [friendly/statquotes#6]
I recently upgraded to R 3.3.2 and reinstalled `statquotes` (v. 0.2) from CRAN. In a clean session, I now get an error. What could have happened?

    > library(statquotes)
    > statquote("Galton")
    Error in .get.sq() : 
      cannot open file 'd:\RCompile\CRANpkg\lib\3.3\statquotes/data/Rdata.rdb': No such file or directory
    > statquote()
    Error in .get.sq() : 
      cannot open file 'd:\RCompile\CRANpkg\lib\3.3\statquotes/data/Rdata.rdb': No such file or directory
    In addition: Warning message:
    In .get.sq() : restarting interrupted promise evaluation
    >

**Comment by mattsigal** [comment]
I'm seeing the same behaviour on my computer.  No errors upon installation, only when querying a quote.

```
> library(statquotes)
> statquote()
Error in .get.sq() : 
  cannot open file '/Builds/CRAN-QA-Simon/packages/mavericks-x86_64/Rlib/3.3/statquotes/data/Rdata.rdb': No such file or directory
```

**Comment by mattsigal** [comment]
It looks like it is searching for `Rdata.rdb` but our the file in our data fidrectory is actually called `quotes.Rdata`?  Looking at the directory, quotes.Rdata actually appears in 3 places: data, inst, and tex. Is this correct?

**Comment by mattsigal** [comment]
If I download the package from source, and run the lines in `statquote.R` line by line, `statquote()` works as expected...

**Comment by mattsigal** [comment]
Seems the issue is in these lines in `statquote.R`:

```
.sq.env <- new.env()
data(quotes, package = 'statquotes', envir = .sq.env)
.get.sq <- function() .sq.env$quotes
```
Either the `.sq.env` is not being created when the function is called, or the `quotes` dataframe is not being properly placed into it.

**Comment by philchalmers** [comment]
Can't confirm, it works fine for me on the same R version on Linux. Though this example `statquote("Galton")` never worked, you want `statquote(source = "Galton")`. I'll switch to a windows OS to see if I can replicate.

**Comment by philchalmers** [comment]
Confirmed on Win 10 and patched. Not sure why 093c484b541e5a111b281a14a25d7ef131ceb4b2 is needed now; must be something new regarding when the objects are sourced at the startup. Feel free to reopen if the issue persists.

**Comment by friendly** [comment]
Thanks so much, Phil.
