### ISSUE TITLE
Error in .get.sq() -- need to push 0.2-1 to CRAN

### ISSUE THREAD

**Issue by friendly** [friendly/statquotes#7]
I just installed R version 3.4.1 and installed all my packages, including `statquotes_0.2` from CRAN. On first use, I get errors:

    > statquote(source="Tukey")
    Error in .get.sq() : 
      cannot open file 'd:\RCompile\CRANpkg\lib\3.4\statquotes/data/Rdata.rdb': No such file or directory
    > statquote()
    Error in .get.sq() : 
      cannot open file 'd:\RCompile\CRANpkg\lib\3.4\statquotes/data/Rdata.rdb': No such file or directory
    In addition: Warning message:
    In .get.sq() : restarting interrupted promise evaluation
    > 

If I install v. 0.2-1 from github, these errors don't occur.  We need to submit the new version to CRAN.
Before I do, are there any other things to take care of?

**Comment by mattsigal** [comment]
Nothing comes to mind on my end, and hopefully v. 0.2-1 solves that issue.

**Comment by philchalmers** [comment]
@mattsigal it does, that's what #6 was about :). Other than creating a more pull-able (?) storage method for front-end users to contribute their quotes, I can't think of anything pressing that needs to be added.

**Comment by friendly** [comment]
OK, I'll prepare 0.2-1 for release. Sorry for not checking #6 first

For the future, it would be nice at least for **us** to be able to easily add new quotes.

**Comment by mattsigal** [comment]
@philchalmers - that could be a really cool feature. Perhaps something like a function that users pass the quote and citation information to in R that pushes to a Google Sheets document or something and auto-populates with the proper fields. Then we could periodically run a script to grab them and pull them into the database?  I'd be happy to work on something like that -- as soon as my full dissertation draft is with the committee ;)

**Comment by philchalmers** [comment]
I was thinking something simpler, like just a `.csv` file would be fine to work with on both sides, and then have `statquotes` points to this internally. That would be easier to have users add lines via a pull request. We should still review contributions, rather than having something that is less supervised, so that we have more control over the quality.

**Comment by friendly** [comment]
I agree that something simpler, say a simple way to add to a `.csv` file is what is needed.  This discussion should be moved to a new issue, which I'll do.

**Comment by philchalmers** [comment]
Way ahead of you... see #4 :)

**Comment by friendly** [comment]
I'm now working on resolving this issue and updating the package stuff for submission to CRAN.
