### ISSUE TITLE
Make it easier to add new statquotes

### ISSUE THREAD

**Issue by friendly** [friendly/statquotes#8]
This issue continues the discussion started in #7.

For concreteness, let me propose a new function, `addquote()` that somehow gathers the required information and appends to (a copy of?) the `.csv` file.  It could prompt for NULL arguments, then clean the fields as required, etc.  

There must be some similar mechanism that Achim Zeillis uses for the `fortunes` package.

**Comment by philchalmers** [comment]
@friendly could you check out the `devel` branch for the beginning of this? I've ported what I could from the original `.tex` files into a suitable `.csv` (https://github.com/friendly/statquotes/blob/devel/inst/quotes.csv). But, I think it should be checked more closely in case there's non-standard quotations that were not picked up in our `grep` search.

Exposing this text file on Github makes it easier for users just to click "edit", which then automatically turns into a pull request without any need for the user to know git. Also, as far as I can tell `fortunes` does not have an easy way to add quotes. I think they are just done manually by Achim through email.

**Comment by friendly** [comment]
@philchalmers Just took a look at this.  I also have some additional quotes to add.  
Shall we pull your stuff in `inst/` into the package?

**Comment by philchalmers** [comment]
I just rebased this branch, and ran the new `quotes2RData()` function, so it's up-to-date (feel free to modify the format of this function b.t.w.; it's just a working version but could be made more accessible). A merge/pull to the master branch would create no conflicts and will switch gears to using this master `.csv` file approach.

In this branch, all changes are made to the master `.csv` file, and prior to a major CRAN release the function `quotes2RData()` must be run to update the internal `.Rdata` file.

**Comment by friendly** [comment]
I just tried adding some quotes (OK) and ran `quotes2RData()` (OK).  Next steps:

* Bump package version in `devel` ?
* merge / pull to `master` ?
* anything else?

**Comment by philchalmers** [comment]
Yes, yes, no.
