### ISSUE TITLE
statquotes 0.2.2 ready to submit to CRAN

### ISSUE THREAD

**Issue by friendly** [friendly/statquotes#9]
I updated all man/ files, the README.md, DESCRIPTION, etc., then ran `devtools::build_win()`, which passed. 
So, I updated `cran-comments.md` and am now ready to submit this to CRAN.  This is all on the master branch.

Let me know if there is any reason for me to hold off.

**Comment by philchalmers** [comment]
I'm okay with a release. Thanks.

**Comment by friendly** [comment]
Submitted, and now accepted on CRAN
